# Generated by Django 4.2.15 on 2024-09-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-epic', '-created_at']},
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
