# Generated by Django 4.2.15 on 2024-08-30 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('epics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='task_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_list', to='tasks.task'),
        ),
    ]
