# Generated by Django 4.2.15 on 2024-08-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='status',
            field=models.CharField(choices=[(1, 'To-do'), (2, 'In Progress'), (3, 'Completed'), (4, 'Backlog')], default=1, max_length=15),
        ),
    ]
