# Generated by Django 4.2.15 on 2024-09-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epics', '0005_epic_profile_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epic',
            name='profile_list',
        ),
    ]
